version: "3.7"

services:
  insecureinc:
    image: securecodingdojo/insecure.inc
    build:
      context: ./insecureinc
      dockerfile: Dockerfile.insecureinc
    restart: "always" #change to always if you want the image to auto start
    ports:
      - "8080:8080"
    networks:
      - insecure
    environment:
       - CHALLENGE_MASTER_SALT

networks:
  insecure:
