# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0	

version: "3.8"

services:
  host1:
    image: securecodingdojo/hackerden-host1
    build:
      context: .
      dockerfile: Dockerfile.host1
    restart: "always" 
    expose:
      - "22"
    networks:
      hden:
        aliases:
          - host1

  host2:
    image: securecodingdojo/hackerden-host2
    build:
      context: .
      dockerfile: Dockerfile.host2
    restart: "always"
    environment:
      - SECRET2=FLAG-xxe
      - SECRET3=FLAG-deserialization
    expose:
      - "8080"
    networks:
      hden:
        aliases:
          - host2

  front:
    image: securecodingdojo/hackerden-front
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: "always" 
    ports:
      - "3000:3000"
    environment:
       - CHALLENGE_MASTER_SALT
       - HDEN_SIGN_SECRET
       - HDEN_AUTH_SECRET
       - COINMINER_SSH_HOST=host1
       - COMMAND_PROC_URL=http://host2:8080/commandproc
    networks:
      hden:
        aliases:
          - front



networks:
  hden:
